### ISSUE TITLE
Error with authentication

### ISSUE THREAD

**Issue by filiptronicek** [edin-m/google-photos-sync#1]
When I tried to run 'node app' it returns this error:
TypeError: Cannot read property 'auth_uri' of undefined
    at AuthService._setAuthorizationParameters (D:\Downloads\google-photos-sync-master(1)\google-photos-sync-master\google-auth.js:138:31)
    at Promise (D:\Downloads\google-photos-sync-master(1)\google-photos-sync-master\google-auth.js:98:30)
    at new Promise (<anonymous>)
    at AuthService._authenticate (D:\Downloads\google-photos-sync-master(1)\google-photos-sync-master\google-auth.js:97:16)
    at AuthService.authenticate (D:\Downloads\google-photos-sync-master(1)\google-photos-sync-master\google-auth.js:83:25)
    at main (D:\Downloads\google-photos-sync-master(1)\google-photos-sync-master\app.js:30:23)
    at Object.<anonymous> (D:\Downloads\google-photos-sync-master(1)\google-photos-sync-master\app.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by edin-m** [comment]
Do you have `secrets/credentials.json`?
You can generate it from your Google Dev Console. Select Create credentials > OAuth client ID. Make sure to put `http://localhost:3001/oauth2redirect` and `http://localhost:3001/token` for Authorized redirect URIs. Download the credentials json, and put it into the `secrets` folder.
